#%RAML 1.0 NamedExample
lazy-fashions-example:
  -
    AccountNumber: 100
    Name : chris
    phone: 5647652478
    shipping city: chennai
    shipping state: TN
    shipping country: India
  -
    AccountNumber: 101
    Name : Tom
    phone: 5647652456 
    shipping city: madurai
    shipping state: TN
    shipping country: India